{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "toc": true
   },
   "source": [
    "<h1>Table of Contents<span class=\"tocSkip\"></span></h1>\n",
    "<div class=\"toc\"><ul class=\"toc-item\"></ul></div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# NeurIPS - Run Losses\n",
    "\n",
    "Goal : have a table that compares the different losses on MNIST.\n",
    "\n",
    "Data : MNIST\n",
    "\n",
    "Models : AttnNPFXL and ConvNPFXL for CNPFLoss, NLLLloss, ISLoss, ElboLoss\n",
    "\n",
    "Runs : 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "os.chdir(\"..\")\n",
    "\n",
    "import submitit\n",
    "\n",
    "from train_imgs import main, parse_arguments\n",
    "from results import get_exp_args\n",
    "\n",
    "class Run:\n",
    "    def checkpoint(self, args):\n",
    "        \"\"\"Resubmits the same callable with the same arguments but makes sure continnue from last chckpnt.\"\"\"\n",
    "        args.is_continue_train = True\n",
    "        return submitit.utils.DelayedSubmission(self, args)\n",
    "\n",
    "    def __call__(self, args):\n",
    "        job_env = submitit.utils.JobEnvironment()\n",
    "        args.starting_run = args.starting_run * job_env.num_tasks + job_env.local_rank\n",
    "        return main(args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_reeval(name, n_test, bs=16, is_iw=False):\n",
    "    name = f\"{name}_{str(n_test)}\"\n",
    "    if is_iw:\n",
    "        name += \"_iw\"\n",
    "        \n",
    "    args = get_exp_args(name, is_load=False, is_reeval=True)\n",
    "    args = [arg for arg in args if (arg.dataset == \"mnist\" and arg.runs <= 3)]\n",
    "    for arg in args:\n",
    "        arg.n_z_samples_test = n_test\n",
    "        arg.batch_size=bs\n",
    "        if is_iw:\n",
    "            arg.is_iw_eval=True\n",
    "    return args"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "args=[]\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 8, bs=16))\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 2048, bs=1))\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 8, bs=16, is_iw=True))\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 2048, bs=1, is_iw=True))\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 32, bs=16, is_iw=True))\n",
    "args.extend(load_reeval(\"exp_final3_losses\", 512, bs=1, is_iw=True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "executor=submitit.SlurmExecutor(folder=\"logs/%j\", max_num_timeout=3)\n",
    "executor.update_parameters(num_gpus=1, \n",
    "                           time=60*24,  \n",
    "                           cpus_per_task=10, \n",
    "                           mem='32GB',\n",
    "                           partition=\"dev\",\n",
    "                           comment=\"neurips\",\n",
    "                           constraint=\"volta32gb\"\n",
    "                          )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "jobs = executor.map_array(Run(), args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "############################################################"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[SlurmJob<job_id=27231440_0, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_1, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_2, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_3, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_4, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_5, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_6, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_7, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_8, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_9, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_10, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_11, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_12, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_13, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_14, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_15, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_16, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_17, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_18, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_19, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_20, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_21, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_22, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_23, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_24, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_25, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_26, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_27, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_28, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_29, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_30, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_31, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_32, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_33, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_34, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_35, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_36, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_37, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_38, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_39, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_40, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_41, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_42, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_43, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_44, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_45, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_46, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_47, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_48, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_49, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_50, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_51, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_52, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_53, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_54, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_55, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_56, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_57, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_58, task_id=0, state=\"COMPLETED\">,\n",
       " SlurmJob<job_id=27231440_59, task_id=0, state=\"COMPLETED\">]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "jobs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,739) - Starting with JobEnvironment(job_id=27221377_0, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,739) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_0/27221377_0_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:27,225) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,739) - Starting with JobEnvironment(job_id=27221377_1, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,739) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_1/27221377_1_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,965) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,918) - Starting with JobEnvironment(job_id=27221377_2, hostname=learnfair0349, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,918) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_2/27221377_2_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_2 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:27,206) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,734) - Starting with JobEnvironment(job_id=27221377_3, hostname=learnfair0839, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,734) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_3/27221377_3_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_3 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,420) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,888) - Starting with JobEnvironment(job_id=27221377_4, hostname=learnfair0853, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,888) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_4/27221377_4_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:27,672) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,865) - Starting with JobEnvironment(job_id=27221377_5, hostname=learnfair0857, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,865) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_5/27221377_5_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,738) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,865) - Starting with JobEnvironment(job_id=27221377_6, hostname=learnfair0857, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,865) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_6/27221377_6_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,443) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,885) - Starting with JobEnvironment(job_id=27221377_7, hostname=learnfair0901, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,886) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_7/27221377_7_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_2 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,653) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:15:15,885) - Starting with JobEnvironment(job_id=27221377_8, hostname=learnfair0901, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:15:15,886) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_8/27221377_8_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_3 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:15:26,654) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,607) - Starting with JobEnvironment(job_id=27221377_9, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,607) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_9/27221377_9_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:19,006) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,607) - Starting with JobEnvironment(job_id=27221377_10, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,607) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_10/27221377_10_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_ElboLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:18,896) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,607) - Starting with JobEnvironment(job_id=27221377_11, hostname=learnfair0349, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,608) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_11/27221377_11_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_ElboLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:19,236) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,608) - Starting with JobEnvironment(job_id=27221377_12, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,609) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_12/27221377_12_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_ElboLNPF/run_2 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:19,166) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,608) - Starting with JobEnvironment(job_id=27221377_13, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,609) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_13/27221377_13_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_ElboLNPF/run_3 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:19,221) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,606) - Starting with JobEnvironment(job_id=27221377_14, hostname=learnfair0839, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,606) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_14/27221377_14_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_ElboLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:18,531) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:07,606) - Starting with JobEnvironment(job_id=27221377_15, hostname=learnfair0839, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:07,606) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_15/27221377_15_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_ElboLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:19:18,432) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:57,197) - Starting with JobEnvironment(job_id=27221377_16, hostname=learnfair0853, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:57,198) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_16/27221377_16_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_ElboLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:20:09,251) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:19:57,197) - Starting with JobEnvironment(job_id=27221377_17, hostname=learnfair0853, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:19:57,198) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_17/27221377_17_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_ElboLNPF/run_2 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:20:09,176) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Starting with JobEnvironment(job_id=27221377_18, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_18/27221377_18_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_ElboLNPF/run_3 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,420) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Starting with JobEnvironment(job_id=27221377_19, hostname=learnfair0837, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_19/27221377_19_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_ElboLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,051) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Starting with JobEnvironment(job_id=27221377_20, hostname=learnfair0330, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_20/27221377_20_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,423) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,313) - Starting with JobEnvironment(job_id=27221377_21, hostname=learnfair0349, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,314) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_21/27221377_21_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,680) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Starting with JobEnvironment(job_id=27221377_22, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,313) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_22/27221377_22_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_2 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,804) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Starting with JobEnvironment(job_id=27221377_23, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,313) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_23/27221377_23_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_3 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,920) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Starting with JobEnvironment(job_id=27221377_24, hostname=learnfair0839, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_24/27221377_24_submitted.pkl\n",
      "\n",
      "--- Loading mnist/ConvNPFXL_NllLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:23:59,904) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Starting with JobEnvironment(job_id=27221377_25, hostname=learnfair0839, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,311) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_25/27221377_25_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_0 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:23:59,889) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Starting with JobEnvironment(job_id=27221377_26, hostname=learnfair0853, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:23:49,312) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_26/27221377_26_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_1 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:24:00,504) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:30:16,317) - Starting with JobEnvironment(job_id=27221377_29, hostname=learnfair0330, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:30:16,317) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_29/27221377_29_submitted.pkl\n",
      "\n",
      "--- Loading mnist/SelfAttnNPF_NllLNPF/run_4 ---\n",
      "\n",
      "submitit ERROR (2020-06-04 03:30:27,598) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:31:09,383) - Starting with JobEnvironment(job_id=27221377_31, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:31:09,383) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_31/27221377_31_submitted.pkl\n",
      "submitit ERROR (2020-06-04 03:31:16,887) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "submitit INFO (2020-06-04 03:31:11,577) - Starting with JobEnvironment(job_id=27221377_32, hostname=learnfair0761, local_rank=0(1), node=0(1), global_rank=0(1))\n",
      "submitit INFO (2020-06-04 03:31:11,577) - Loading pickle: /private/home/yannd/projects/NPF/logs/27221377_32/27221377_32_submitted.pkl\n",
      "submitit ERROR (2020-06-04 03:31:16,886) - Submitted job triggered an exception\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "for j in jobs:\n",
    "    print(\"--------------------------------\")\n",
    "    print(j.stdout())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:15:27,225) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_NllLNPF/run_0/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221379.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:15:26,965) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_NllLNPF/run_1/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221380.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:15:27,206) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_NllLNPF/run_2/history.json'\n",
      "srun: error: learnfair0349: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221381.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:15:26,420) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_NllLNPF/run_3/history.json'\n",
      "srun: error: learnfair0839: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221382.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:15:27,672) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_NllLNPF/run_4/history.json'\n",
      "srun: error: learnfair0853: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221383.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:15:26,738) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_NllLNPF/run_0/history.json'\n",
      "srun: error: learnfair0857: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221384.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:15:26,443) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_NllLNPF/run_1/history.json'\n",
      "srun: error: learnfair0857: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221385.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:15:26,653) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_NllLNPF/run_2/history.json'\n",
      "srun: error: learnfair0901: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221386.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:15:26,654) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_NllLNPF/run_3/history.json'\n",
      "srun: error: learnfair0901: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221387.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:19:19,006) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_NllLNPF/run_4/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221413.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:19:18,896) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_ElboLNPF/run_0/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221414.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:19:19,236) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_ElboLNPF/run_1/history.json'\n",
      "srun: error: learnfair0349: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221415.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:19:19,166) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_ElboLNPF/run_2/history.json'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221416.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:19:19,221) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_ElboLNPF/run_3/history.json'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221417.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:19:18,531) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/ConvNPFXL_ElboLNPF/run_4/history.json'\n",
      "srun: error: learnfair0839: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221418.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:19:18,432) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_ElboLNPF/run_0/history.json'\n",
      "srun: error: learnfair0839: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221419.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:20:09,251) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_ElboLNPF/run_1/history.json'\n",
      "srun: error: learnfair0853: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221420.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:20:09,176) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_ElboLNPF/run_2/history.json'\n",
      "srun: error: learnfair0853: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221421.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:24:00,420) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_ElboLNPF/run_3/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221446.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:24:00,051) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_8/mnist/SelfAttnNPF_ElboLNPF/run_4/history.json'\n",
      "srun: error: learnfair0837: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221447.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:24:00,423) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/ConvNPFXL_NllLNPF/run_0/history.json'\n",
      "srun: error: learnfair0330: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221448.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:24:00,680) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/ConvNPFXL_NllLNPF/run_1/history.json'\n",
      "srun: error: learnfair0349: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221449.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:24:00,804) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/ConvNPFXL_NllLNPF/run_2/history.json'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221450.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:24:00,920) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/ConvNPFXL_NllLNPF/run_3/history.json'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221451.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:23:59,904) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/ConvNPFXL_NllLNPF/run_4/history.json'\n",
      "srun: error: learnfair0839: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221452.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:23:59,889) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/SelfAttnNPF_NllLNPF/run_0/history.json'\n",
      "srun: error: learnfair0839: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221453.0\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:24:00,504) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/SelfAttnNPF_NllLNPF/run_1/history.json'\n",
      "srun: error: learnfair0853: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221454.0\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "/private/home/yannd/projects/NPF/neuralproc/architectures/mlp.py:67: UserWarning: hidden_size=32 smaller than output=128 and input=128. Setting it to 128.\n",
      "  warnings.warn(txt.format(hidden_size, output_size, input_size, self.hidden_size))\n",
      "submitit ERROR (2020-06-04 03:30:27,598) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 324, in main\n",
      "    is_reeval=args.is_reeval,\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 263, in train\n",
      "    **kwargs,\n",
      "  File \"/private/home/yannd/projects/NPF/utils/train.py\", line 242, in train_models\n",
      "    trainer.load_params(checkpoint=chckpt)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/net.py\", line 1644, in load_params\n",
      "    self.history = History.from_file(checkpoint.f_history_)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/history.py\", line 161, in from_file\n",
      "    with open_file_like(f, 'r') as fp:\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/contextlib.py\", line 112, in __enter__\n",
      "    return next(self.gen)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/skorch/utils.py\", line 433, in open_file_like\n",
      "    f = open(f, mode)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'results/neurips/exp_final3_losses_2048/mnist/SelfAttnNPF_NllLNPF/run_4/history.json'\n",
      "srun: error: learnfair0330: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221477.0\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:31:16,887) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 290, in main\n",
      "    partial(get_Loss(args.loss), is_force_mle_eval=not args.is_iw_eval),\n",
      "AttributeError: 'Namespace' object has no attribute 'is_iw_eval'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221479.0\n",
      "\n",
      "--------------------------------\n",
      "submitit ERROR (2020-06-04 03:31:16,886) - Submitted job triggered an exception\n",
      "ERROR:submitit:Submitted job triggered an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/_submit.py\", line 6, in <module>\n",
      "    submitit_main()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 186, in submitit_main\n",
      "    process_job(args.folder)\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 179, in process_job\n",
      "    raise error\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/submission.py\", line 168, in process_job\n",
      "    result = delayed.result()\n",
      "  File \"/private/home/yannd/.conda/envs/neuralproc/lib/python3.7/site-packages/submitit/utils.py\", line 122, in result\n",
      "    self._result = self.function(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-1-7d4d48403197>\", line 19, in __call__\n",
      "  File \"/private/home/yannd/projects/NPF/train_imgs.py\", line 290, in main\n",
      "    partial(get_Loss(args.loss), is_force_mle_eval=not args.is_iw_eval),\n",
      "AttributeError: 'Namespace' object has no attribute 'is_iw_eval'\n",
      "srun: error: learnfair0761: task 0: Exited with exit code 1\n",
      "srun: Terminating job step 27221480.0\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n",
      "--------------------------------\n",
      "None\n"
     ]
    }
   ],
   "source": [
    "for j in jobs:\n",
    "    print(\"--------------------------------\")\n",
    "    print(j.stderr())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "for job in jobs:\n",
    "    job.cancel()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": true,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": true,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
